### ISSUE TITLE
Ability to prevent console.log when custom logger provided

### ISSUE THREAD

**Issue by PredokMiF** [vitaly-t/pg-monitor#22] opened 2019-09-19 11:09 UTC
To prevent `console.log` when custom logger provided, I must mutate incoming config to prevent default behaviour. It isnt documented and wery stange setup method

```javascript
monitor.setLog((msg, info) => {
    const { time, event, ...args } = info
    info.display = false
    logger.debug(event, args)
})
```

**Comment by vitaly-t** [comment] 2019-09-19 14:57
[What isn't documented?](https://github.com/vitaly-t/pg-monitor#info)

> wery stange setup

It is a normal, documented feature. Especially considering that few people ever need to deactivate the default output.

**Comment by PredokMiF** [comment] 2019-09-20 09:47
Maby be better format like:
```javascript
monitor.setLog({ defaultLog: false }, (msg, info) => {...}
```
I think it is better rather then mutate incoming props insite collback

**Comment by vitaly-t** [comment] 2019-09-20 14:44
The existing architecture was designed this way to let you cancel output of messages based on their type and content, which requires live intercept.

**Comment by PredokMiF** [comment] 2019-09-20 19:14
I understand, that this architecture provide by flexibitlity of code behaviour, but IMHO in real world we get 2 cases. First: all logs allways pipes to stdout to filesystem. Second: we have custom logger and controll it in enother code, not monitor callback. As I said I understand you point of view and cant push on you to provide changes to the stable module. We can close issue.

**Comment by vitaly-t** [comment] 2019-09-20 20:13
You can call it a minor inconvenience, but for all means and purposes, it works, and it works without issues. And since this is primarily a DEV-module, for SQL debugging, and not really a production module, it can do away without the extra finesse. So, I'm closing the issue.

**Closed as completed by vitaly-t** 2019-09-20 20:13 UTC

**Comment by PredokMiF** [comment] 2019-09-20 20:41
В очередной раз приятно удивлен Вашей общительностью. Рад что есть живые модули, за которыми присматривают )

**Comment by vitaly-t** [comment] 2019-10-11 12:58
[This](https://github.com/vitaly-t/pg-monitor/issues/25) will present an opportunity for all kinds of changes.
